spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wa_storage_service
    username: postgres
    password: 4589
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
  jpa:
    properties:
      show-sql: true

health:
  kafka:
    retry-interval-ms: 1000
    max-retries: 3

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS:Y5ncOVqSI/HnJisBxE0TDsk/3cMP/FbwMDL+elybXkqsmpjNIqbjwCCOM8wTznVkqxeYZqf+ppsr4wzHNt8peA==}

